apiVersion: v1
kind: ServiceAccount
metadata:
  name: krios-scheduler-account
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krios-scheduler-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: krios-scheduler-account
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krios-scheduler-as-volume-scheduler
subjects:
- kind: ServiceAccount
  name: krios-scheduler-account
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: krios-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        version: second
    spec:
      serviceAccountName: krios-scheduler-account
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""  # Ensure this matches the label on your control plane nodes
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - image: vaibhavb007/krios-scheduler
        name: krios-scheduler
        securityContext:
          privileged: false
        volumeMounts: []
        imagePullPolicy: Always 
      hostNetwork: false
      hostPID: false
      volumes: []